// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3_aauHhmg1F0_rf7eHUVUK2svgrcqZpk',
    appId: '1:445028058844:web:91f44316786ba685635619',
    messagingSenderId: '445028058844',
    projectId: 'khoras-5-6',
    authDomain: 'khoras-5-6.firebaseapp.com',
    storageBucket: 'khoras-5-6.firebasestorage.app',
    measurementId: 'G-XQRWFGYBWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuqkF67R-bDmuepLZHS0BgMj59rxsu-Dk',
    appId: '1:445028058844:android:1abc5a4e8f9273b7635619',
    messagingSenderId: '445028058844',
    projectId: 'khoras-5-6',
    storageBucket: 'khoras-5-6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRnN-zM2wZ6_ODM5DadF9iBcixmH-UkbU',
    appId: '1:445028058844:ios:deb7d5e17a4864f3635619',
    messagingSenderId: '445028058844',
    projectId: 'khoras-5-6',
    storageBucket: 'khoras-5-6.firebasestorage.app',
    iosBundleId: 'com.example.khoras56',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-HPHXlW-ZS3z0TK9b5LIhIUVbbWclypM',
    appId: '1:282688463082:ios:c2aa3f1e473471c6edf793',
    messagingSenderId: '282688463082',
    projectId: 'argenworld-44f6d',
    storageBucket: 'argenworld-44f6d.appspot.com',
    iosBundleId: 'com.example.thanawy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU2Kypx3TLtspMk3WTpAUucEMcEi_Src0',
    appId: '1:282688463082:web:01900a4d2170c65fedf793',
    messagingSenderId: '282688463082',
    projectId: 'argenworld-44f6d',
    authDomain: 'argenworld-44f6d.firebaseapp.com',
    storageBucket: 'argenworld-44f6d.appspot.com',
    measurementId: 'G-V9RH1TZW4G',
  );

}