name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: Build iOS IPA
    runs-on: macos-latest

    steps:
      # ✅ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # ✅ Set up Flutter environment
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # ✅ Install Flutter dependencies
      - name: Install Flutter dependencies
        run: flutter pub get

      # ✅ Precache iOS artifacts
      - name: Precache iOS artifacts
        run: flutter precache --ios

      # ✅ Clean and set up iOS environment
      - name: Clean and set up iOS environment
        run: |
          flutter doctor -v
          flutter clean
          flutter pub get
          cd ios
          pod deintegrate || true
          rm -rf Pods Podfile.lock
          pod install --repo-update
          cd ..

      # ✅ Build iOS app (No codesign)
      - name: Build iOS app
        run: |
          set -o pipefail
          flutter build ios --release --no-codesign | xcpretty

      # ✅ Create Payload directory for IPA packaging
      - name: Create Payload directory
        run: |
          mkdir -p Payload
          mv Runner.app Payload/
        working-directory: build/ios/iphoneos

      # ✅ Zip the IPA file
      - name: Create IPA
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      # ✅ Upload IPA to GitHub release
      - name: Upload IPA to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "Generated iOS IPA build"
