name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: Build iOS IPA
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Precache iOS artifacts
        run: flutter precache --ios

      - name: Set up Flutter iOS environment
        run: |
          flutter doctor -v  # For debugging
          flutter clean      # Reset build state
          flutter pub get    # Regenerate dependencies
          cd ios
          pod deintegrate || true  # Clean up any broken CocoaPods state
          rm -rf Pods Podfile.lock  # Remove stale files
          cd ..

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS app
        run: flutter build ios --release --no-codesign

      - name: Create Payload directory
        run: |
          mkdir -p Payload
          mv Runner.app Payload/
        working-directory: build/ios/iphoneos

      - name: Zip IPA
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload IPA to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "Congrats"