name: Build iOS Ipa

on:
  workflow_dispatch:
jobs:
  build-ios:
    name: Build iOS Ipa
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter pub get

      - name: Ensure Podfile exists
        run: |
          if [ ! -f ios/Podfile ]; then
            echo "Podfile not found. Generating it..."
            cd ios
            touch Podfile
            echo "platform :ios, '13.0'" >> Podfile
            echo "use_frameworks!" >> Podfile
            echo "target 'Runner' do" >> Podfile
            echo "  # Add your pods here" >> Podfile
            echo "end" >> Podfile
            cd ..
          fi

      - run: pod repo update
        working-directory: ios

      - run: flutter build ios --release --no-codesign

      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "Congrats"