name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: Build iOS IPA
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Ruby for CocoaPods
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      # Set up Flutter environment
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      # Install Flutter dependencies
      - name: Install Flutter dependencies
        run: flutter pub get

      # Precache iOS artifacts
      - name: Precache iOS artifacts
        run: flutter precache --ios

      # Clean and set up the iOS environment
      - name: Set up Flutter iOS environment
        run: |
          flutter doctor -v
          flutter clean
          flutter pub get
          cd ios
          pod deintegrate || true
          rm -rf Pods Podfile.lock
          pod cache clean --all
          cd ..

      # Install CocoaPods dependencies
      - name: Install CocoaPods dependencies
        run: |
          cd ios
          gem install cocoapods -v 1.15.2  # Use a slightly older, stable version known to work with Flutter
          pod install --repo-update
          cd ..

      # Build iOS app
      - name: Build iOS app
        run: |
          set -o pipefail
          flutter build ios --release --no-codesign

      # Archive and export IPA
      - name: Archive and export IPA
        run: |
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -R Runner.app Payload/
          zip -qq -r -9 FlutterIpaExport.ipa Payload
          cd ../../..

      # Upload IPA to GitHub release
      - name: Upload IPA to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "Congrats"